### ISSUE TITLE
The constructor with parameters has been removed in JSZip 3.0

### ISSUE THREAD

**Issue by pikebishop1** [DxCx/ts-xlsx#1]
thanks for developing this - i'm getting the error in the subject line and after researching some it looks like js-xlsx only works with jzip 2.4 - can you have a look at this.

**Comment by DxCx** [comment]
hi @pikebishop1 sorry, i was with limited connection in the past days..
is this still relevant to you?
do you have more info to share now?

**Comment by pikebishop1** [comment]
Hi - i'm getting the browser error when i try to compile my code 

> The constructor with parameters has been removed in JSZip 3.0

when reading up on the error i found the below issue in the js-xlxs github page
- [408](https://github.com/SheetJS/js-xlsx/issues/408)

**Comment by DxCx** [comment]
cool thanks,
it pretty much means that there is nothing much to do but downgrade jszip in package.json
are you willing to contriubute and open a PR? or i'll do it?
