### ISSUE TITLE
Update XLSX to 0.10

### ISSUE THREAD

**Issue by negberts** [DxCx/ts-xlsx#14]
I was trying to create a PR for this change but got a 403 error. :(

**Comment by DxCx** [comment]
403 error? where?
i'll accept the PR with pleasure 👍

**Comment by negberts** [comment]
When trying to upload the PR from Visual Studio. Maybe you need to add me to contributors or something?

**Comment by DxCx** [comment]
oh, you need to fork the repo into your own user, open a branch there, add the commit and push the branch.
after that you can get into github web and open the PR against this repo ;)
