### ISSUE TITLE
License reported differently between github and npmjs.com

### ISSUE THREAD

**Issue by dereklin** [DxCx/ts-xlsx#20]
I reported this issue: https://github.com/davglass/license-checker/issues/99

It turned out that the license is listed differently between this github repo and npmjs.com registry.

Could you make them the same?

**Comment by DxCx** [comment]
hi @dereklin 
As written in README & also in npm
this package was used to provide only typings for xlsx library.
xlsx now offers typings embeded, because of that this package is deprecated.
please migrate to [xlsx](https://github.com/SheetJS/js-xlsx) instead

**Comment by dereklin** [comment]
@DxCx Thanks!
