### ISSUE TITLE
Error occurring while reading excel file. 

### ISSUE THREAD

**Issue by ganesh-phadtare** [DxCx/ts-xlsx#22]
I am using the package for reading uploaded excel file. While uploading excel I am getting below error.
`Cannot read property 'replace' of undefined`

The package is working properly in the case of normal excel, but when we set the data-validations rule to **column** then above error is occurring. 

Data-validations individual cells is also working fine. 

Please let me know how can I fix this or is there any workaround for the same.

**Comment by DxCx** [comment]
hey @ganesh-phadtare 
this package created before the original xlsx had typescript support.
nowadays xlsx supports typescript out of the box, and this repo is deprecated.

please try and use mainstream xlsx package and if you have any issue, open a ticket there.
