### ISSUE TITLE
Any example on writeFile function?

### ISSUE THREAD

**Issue by zh-wowtv** [DxCx/ts-xlsx#7]
> XLSX.writeFile(workbook, 'out.xls');

What I want is to write data to a local file out.xls. Is this possible? 

Or any example on how to write to a xls file from json object? 

Thanks.

**Comment by DxCx** [comment]
there is an example covering read scenerio,
are you planing to use the library on server side or client side?
because writing file on client side (fs) doesn't really work..

**Comment by zh-wowtv** [comment]
@DxCx I planed to generate the `xls` in client side. But there is another method `write` . Now the question become how am I suppose to generate a Blob with `xls` format by ts-xlsx so that I can save it by FileSaver. Is that possible? Is there an example on how to generate `xls`? Thanks.

**Comment by DxCx** [comment]
what i've done before is used ts-xlsx to generate the blob.
then convert it to base64 and made the client download it with a link of that base-64.

**Comment by DxCx** [comment]
@zh-wowtv it's being almost 2 weeks with no reply..?

**Comment by zh-wowtv** [comment]
Thanks. I'm using  alasql to generate `xlsx` now. But I got problem when I generate `xls` too.

**Comment by DxCx** [comment]
@zh-wowtv can you eleborate?
i won't be able to assist without any info..
