### ISSUE TITLE
Open local xlxs file

### ISSUE THREAD

**Issue by fredargolo** [DxCx/ts-xlsx#8]
Could you give an example how to open a xlsx file?

**Comment by DxCx** [comment]
@fredargolo do you mean loading file from node and not the browser?

**Comment by fredargolo** [comment]
Exactly.

**Comment by DxCx** [comment]
hey @fredargolo 
this is suppored out of the box by the wrapped library...
please check out https://github.com/SheetJS/js-xlsx/#parsing-workbooks

**Comment by DxCx** [comment]
no respond... reopen if still not working..
